export const GLOBAL_UTIL = "SN_SSA_UTIL";
export const LOAD_NEXT_QUESTION = "SN_SURVEY#LOAD_NEXT_QUESTION";
export const QUESTION_ANSWERED = "SN_SURVEY#QUESTION_ANSWERED";
export const LOAD_PREV_QUESTION = "SN_SURVEY#LOAD_PREVIOUS_QUESTION";
export const SUBMIT_SURVEY = "SN_SURVEY#SURVEY_SUBMITTED";
export const GO_BACK = "SN_SURVEY#SURVEY_GO_BACK";

export const TYPE_SINGLE_SELECT = "RADIO";
export const TYPE_MULTI_SELECT = "CHECKBOX";
export const TYPE_TEXT = "TEXT";
export const TYPE_RATING = "RATING";
